import type { Metadata } from "next";	
import "./globals.css";
import { cn } from "@/lib/utils";
import { poppins, museo } from "@/lib/fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", poppins.variable, museo.variable)}>
      <body
        className={cn("font-sans antialiased")}
      >
        {children}
      </body>
    </html>
  );
}
